# Demyx
# https://demyx.sh

notifications:
  email:
    on_success: never
    on_failure: always

services:
  - docker

env:
  - DEMYX_USERNAME=demyx DEMYX_REPOSITORY=docker-socket-proxy

before_install:
  - /usr/bin/docker pull tecnativa/docker-socket-proxy

script:
  - /usr/bin/docker build --no-cache -t demyx/"$DEMYX_REPOSITORY" .
  - /usr/bin/docker run -dit --name="$DEMYX_REPOSITORY" demyx/"$DEMYX_REPOSITORY"
  - /usr/bin/docker exec "$DEMYX_REPOSITORY" /usr/local/sbin/haproxy -v

after_success:
  - /bin/echo "$DEMYX_PASSWORD" | /usr/bin/docker login -u "$DEMYX_USERNAME" --password-stdin
  - /usr/bin/docker push demyx/"$DEMYX_REPOSITORY"
  - /bin/bash travis.sh
